

const TABBAR_NOR_COLOR = '#dbdbdb'
const TABBAR_SEL_COLOR = '#1296db'
const CUSTOM_BULE_COLOR = '#73b1fa'
const TOUCH_BG_COLOR = '#f6f7fa'
const PAGE_BG_COLOR = '#fff'

module.exports = {
	TABBAR_NOR_COLOR,
	TABBAR_SEL_COLOR,
	CUSTOM_BULE_COLOR,
	TOUCH_BG_COLOR,
	PAGE_BG_COLOR
}